import type { Assessment, TriageState } from "./types";
import { humanize } from "./vocab";
import { REGION_LABEL } from "./regions";
import { urgencyLabel } from "./urgency";

export interface CarePlan {
  headline: string;
  detail: string;
  tone: string;
}

// Concrete, actionable next step for each urgency level (non-diagnostic).
export function carePlan(urgency: string): CarePlan {
  switch (urgency) {
    case "EMERGENCY":
      return { headline: "Call emergency services now", detail: "Call 911 (or your local emergency number). Do not drive yourself.", tone: "var(--u-emergency)" };
    case "URGENT_TODAY":
      return { headline: "Seek care today", detail: "Go to an urgent-care clinic or emergency department today — don't wait until tomorrow.", tone: "var(--u-urgent)" };
    case "DOCTOR_SOON":
      return { headline: "See a doctor within 24–48 hours", detail: "Book an appointment soon. Re-evaluate sooner if anything worsens.", tone: "var(--u-doctor)" };
    case "ROUTINE":
      return { headline: "Book a routine visit", detail: "No urgent signs. Arrange a regular appointment if symptoms persist.", tone: "var(--u-routine)" };
    case "SELF_CARE":
      return { headline: "Self-care and monitor", detail: "Rest and self-care. Re-check if new, different, or worsening symptoms appear.", tone: "var(--u-self)" };
    default:
      return { headline: "Add a few more details", detail: "Describe symptoms, tap the 3D body, or add vitals to get guidance.", tone: "var(--u-none)" };
  }
}

const SEX_LABEL: Record<string, string> = { M: "Male", F: "Female", O: "Other" };
const VITAL_LABEL: Record<string, string> = { hr: "HR", sbp: "Systolic BP", dbp: "Diastolic BP", spo2: "SpO2", temp_c: "Temp", rr: "Resp rate" };

// A clean, copyable summary the user can read out or hand to a clinician.
export function doctorSummary(state: TriageState, a: Assessment | null): string {
  const L: string[] = ["MedScope triage summary — NOT a diagnosis or medical advice.", ""];

  const who: string[] = [];
  if (state.age != null) who.push(`${state.age}y`);
  if (state.sex) who.push(SEX_LABEL[state.sex] ?? state.sex);
  if (who.length) L.push(`Person: ${who.join(", ")}`);

  if (state.symptoms.length) {
    L.push("Symptoms:");
    for (const s of state.symptoms) {
      const dur = s.duration_hours != null ? `, ~${s.duration_hours}h` : "";
      L.push(`  - ${humanize(s.code)} (severity ${s.severity}/10${dur})`);
    }
  }
  if (state.regions.length) L.push(`Areas affected: ${state.regions.map((r) => REGION_LABEL[r] ?? humanize(r)).join(", ")}`);
  if (state.riskFactors.length) L.push(`Risk factors: ${state.riskFactors.map(humanize).join(", ")}`);

  const vitals = Object.entries(state.vitals).filter(([, v]) => v != null);
  if (vitals.length) L.push(`Vitals: ${vitals.map(([k, v]) => `${VITAL_LABEL[k] ?? k} ${v}`).join(", ")}`);

  if (a) {
    L.push("");
    L.push(`Urgency guidance: ${urgencyLabel(a.urgency)} — ${carePlan(a.urgency).headline}`);
    const notes = a.reasons.map((r) => r.message).filter(Boolean);
    if (notes.length) L.push(`Flags/notes: ${notes.join("; ")}`);
  }

  L.push("");
  L.push("Generated by MedScope 3D (research/education prototype). Not HIPAA-compliant. Confirm with a clinician.");
  return L.join("\n");
}
